I LOVE CIRCLES (heartbeat widget)
cwruRobotics/rov-24 pull request #108
Opened 2024-02-06 06:04 UTC by InvincibleRMC

# Pull Request

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Add Circles to the gui.

## Related Tickets & Documents
#71 

- Related Issue #
- Closes #
#107

2024-02-06 06:06 UTC, InvincibleRMC commented
@NoahMollerstuen Your custom styles don't seem to work when running the guis as a node.

2024-02-06 06:20 UTC, NoahMollerstuen commented
> @NoahMollerstuen Your custom styles don't seem to work when running the guis as a node.

What do you mean by that? Styles aren't applied at all, the custom styles aren't applied (but you get dark theme?) or you just can't change the theme? How exactly are you starting the node?

2024-02-06 18:15 UTC, InvincibleRMC commented
When I use ros2 run gui run_pilot or run_operator it runs the guis in lightmode but no custom coloration.

2024-02-09 00:38 UTC, benjaminwp18 requested changes

2024-02-09 00:38 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/circle.py
> +QColorConstantsAlias: TypeAlias = QColor | Qt.GlobalColor | int
Comment this crap

2024-02-09 00:38 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/circle.py
> +class CircleButton(QPushButton):
Investigate using QWidget to do this instead

2024-02-10 17:57 UTC, benjaminwp18 requested changes

2024-02-10 17:57 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/circle.py
> +class CircleButton(QPushButton, CircleInterface):
Delete this

2024-02-10 17:57 UTC, benjaminwp18 commented on src/surface/gui/gui/styles/custom_styles.py
> +class WidgetStateInterface(QWidget):
Rename to something like `StatefulWidget`, `HasWidgetState`, etc.

2024-02-10 17:57 UTC, benjaminwp18 commented on src/surface/gui/gui/styles/custom_styles.py
> +class WidgetStateInterface(QWidget):
Use this everywhere we want statefulness
Move WidgetStyle to be "private" member of WidgetStateInterface

2024-02-10 17:57 UTC, benjaminwp18 commented on src/surface/gui/gui/styles/custom_styles.py
> +class WidgetStateInterface(QWidget):
Put stateful button in here

2024-02-10 17:57 UTC, benjaminwp18 commented on src/surface/gui/gui/styles/custom_styles.py
> +class WidgetStateInterface(QWidget):
Rename all the stateful stuff to Indicator-

2024-02-10 17:57 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/circle.py
> +class CircleInterface(QWidget):
Change to `Circle(QLabel)`

2024-02-10 17:57 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/circle.py
> +class Indicator(Circle, WidgetStateInterface):
`IndicatorCircle`

2024-02-10 17:57 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/heartbeat.py
> +        pi_status_layout = QHBoxLayout()
Rename to `pixhawk_status_layout`

2024-02-10 19:04 UTC, benjaminwp18 approved these changes

2024-02-10 19:04 UTC, merged