Refactor timer widget
cwruRobotics/rov-24 pull request #116
Opened 2024-02-08 23:23 UTC by NoahMollerstuen

# Pull Request

## What type of PR is this? (check all applicable)

- [ x] Refactor
- [ x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Abstract the timer widget into a separate node on the timer laptop communicating over ros with a simpler widget. This allows the global timer to be displayed on multiple places across both guis.

## Related Tickets & Documents
Closes #111

2024-02-17 19:27 UTC, benjaminwp18 requested changes
Move `auxiliary_nodes` and `event_nodes` into a larger `nodes` (`gui_nodes`?) folder with auxiliary and event subfolders

2024-02-17 19:27 UTC, benjaminwp18 commented on src/surface/gui/gui/auxiliary_nodes/timer.py
> +import typing as t
Don't alias this

2024-02-17 19:27 UTC, benjaminwp18 commented on src/rov_msgs/msg/MissionTimer.msg
Rename this file to be less ambiguous with the actual mission timer. `MissionTimerTick`? `MissionTimerBroadcast`?

2024-02-17 19:27 UTC, benjaminwp18 commented on src/rov_msgs/srv/MissionTimerSetRunning.srv
Consider removing this service in favor of an optional set_time field in `MissionTimerSetTime.srv`

2024-02-17 19:27 UTC, benjaminwp18 commented on src/surface/gui/gui/auxiliary_nodes/timer.py
> +            )
To consider when refactoring services: responses to services calls should probably have `is_running=False` when `time_left==0`

2024-02-19 21:59 UTC, InvincibleRMC requested changes

2024-02-19 21:59 UTC, InvincibleRMC commented on src/surface/gui/gui/event_nodes
> +/home/noah/mate/rov-24/src/surface/gui/gui/event_nodes
?

2024-02-19 22:10 UTC, InvincibleRMC requested changes

2024-02-19 22:10 UTC, InvincibleRMC commented on src/surface/gui/gui/gui_nodes/auxiliary_nodes/timer.py
> +DEFAULT_DURATION = 15 * 60  # Seconds
Should this be a Duration object?

2024-02-19 22:10 UTC, InvincibleRMC commented on src/surface/gui/gui/gui_nodes/auxiliary_nodes/timer.py
> +        self.lastTimestamp: Optional[Time] = None
snake_case

2024-02-19 22:10 UTC, InvincibleRMC commented on src/surface/gui/gui/gui_nodes/auxiliary_nodes/timer.py
> +            if self.time_left < Duration(seconds=0):
Constant for Duration(0)?

2024-02-19 22:10 UTC, InvincibleRMC commented on src/surface/gui/gui/widgets/timer.py
> +        super().mission_timer_callback(msg)
I don't think explicit supers should be used unless needed.

2024-02-19 22:19 UTC, benjaminwp18 requested changes
Add docstrings to all methods

2024-02-19 22:19 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/timer.py
>          self.label = QLabel('Label')
This gets used in TimerBase's subclasses. Name it something more better. `timer_display`? `display_label`? `base_display`?

2024-02-21 04:27 UTC, InvincibleRMC submitted a review, later dismissed

2024-02-21 04:49 UTC, NoahMollerstuen commented on src/surface/gui/gui/event_nodes
> +/home/noah/mate/rov-24/src/surface/gui/gui/event_nodes
Idk, this is a normal directory on my machine

2024-02-21 04:52 UTC, NoahMollerstuen commented on src/surface/gui/gui/gui_nodes/auxiliary_nodes/timer.py
> +            if self.time_left < Duration(seconds=0):
Eh, idk if that helps readability at all. This makes it very clear it's a Duration object. I usually count 0 as an acceptable "magic number"

2024-02-21 17:05 UTC, NoahMollerstuen commented
Currently failing the linter because the linter is wrong

2024-02-24 17:57 UTC, benjaminwp18 approved these changes

2024-02-24 19:23 UTC, merged