Thruster assignment
cwruRobotics/rov-24 pull request #122
Opened 2024-02-12 22:05 UTC by InvincibleRMC

# Pull Request

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Add thruster pin changing to debug tab.

## Related Tickets & Documents

- Related Issue
#71 
- Closes #
#12

2024-02-16 00:01 UTC, benjaminwp18 submitted a review, later dismissed

2024-02-16 00:02 UTC, benjaminwp18 requested changes

2024-02-16 00:02 UTC, benjaminwp18 commented on src/pi/pixhawk_communication/launch/mavros_launch.py
>              {"system_id": 255},
Requesting changes

2024-02-16 00:10 UTC, benjaminwp18 requested changes

2024-02-16 00:10 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +import os
Add docstrings to all methods in this file

2024-02-17 21:23 UTC, benjaminwp18 requested changes
1. Load GPIO params into the GUI inputs when the GUI starts
2. Allow running only one thruster at a time

2024-02-17 21:23 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +        if len(pin_input_list) == len(set(pin_input_list)):
Remove this guard

2024-02-17 21:23 UTC, benjaminwp18 commented on src/surface/gui/doc/images/vectored6dof-frame.png
Edit image to make numbers visible and add label for what green/blue mean

2024-02-19 22:51 UTC, benjaminwp18 requested changes
to be continued

2024-02-19 22:51 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +        """Asynchronously tests 1 motor."""
I think you should put the params in this docstring too

2024-02-19 22:51 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +        """Initialize ThrusterBox."""
Add params to docstr

2024-02-19 22:51 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +        """Initialize Widget."""
Make docstring actually document at least a little of what this does
init_widget self-documents that this initializes the widget

2024-02-19 22:51 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +    VALIDATOR: QIntValidator
Make this an instance variable that gets initialized in ThrusterBox's init

2024-02-19 22:51 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +class ThrusterAssignment(QWidget, TestMotorMixin):
ThrusterAssigner?

2024-02-19 22:51 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +    def asnyc_test_motor_for_time(self, motor_index: int, throttle: float = 0.50,
asnyc

2024-02-19 22:51 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +class TestMotorMixin:
rn this creates a static `test_cmd_client` and some methods that don't rely on any kind of instance state

Could this:
 - become a subclass of GUIEventClient (could go in the gui/gui/nodes/auxiliary_nodes dir that Noah's adding to his branch) that we either initialize once or initialize for each widget that uses it?
 - OR
 - Become a set of global methods or static methods in a class that never gets instantiated?

Also, could having test_cmd_client only be initialized once but used in multiple widgets cause threading issues? idk

2024-02-19 23:11 UTC, InvincibleRMC commented
> e continued

😬

2024-02-20 15:24 UTC, InvincibleRMC commented on src/surface/gui/gui/widgets/thruster_tester.py
> +            self.test_cmd_client.send_request_async(
The problem is for motor testing the while loop blocks.

2024-02-21 02:57 UTC, InvincibleRMC commented on src/surface/gui/gui/widgets/thruster_tester.py
> +class TestMotorMixin:
We need to talk about this.

2024-02-21 22:45 UTC, benjaminwp18 requested changes
wip review

2024-02-21 22:45 UTC, benjaminwp18 commented on src/surface/gui/doc/images/vectored6dof-frame.png
Should this be somewhere other than doc/images? I don't think we actually use it in the docs

2024-02-21 22:45 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +                              pin_input + SERVO_FUNCTION_OFFSET).to_parameter_msg()
Could we make a method (`getPin`?) in ThrusterBox that returns `int(self.pin_input.text()) + SERVO_FUNCTION_OFFSET`

2024-02-21 22:45 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +                              val).to_parameter_msg()
Could we make a method (`getDirection`?) in ThrusterBox that returns `REVERSED if x.checkbox.isChecked() else NORMAL`

2024-02-21 22:45 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +                str(params[i].integer_value - SERVO_FUNCTION_OFFSET)
Could we make a method (`setPin`?) in ThrusterBox that returns sets the sets pin_input's text based on the passed integer

2024-02-21 22:45 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +        for i in range(MOTOR_COUNT):
use an enumerate?

2024-02-21 22:45 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +            self.thruster_boxes[i].checkbox.setChecked(set_check)
Could we make a method (`setDirection`?) in ThrusterBox that returns sets the sets the checkbox based on the passed NORMAL, REVERSED, or NO_SPIN value? It could also handle the warning

2024-02-21 22:47 UTC, InvincibleRMC commented on src/surface/gui/doc/images/vectored6dof-frame.png
idk

2024-02-21 22:49 UTC, InvincibleRMC commented on src/surface/gui/gui/widgets/thruster_tester.py
> +        for i in range(MOTOR_COUNT):
I mean I guess you could use an enumerate and then a range

2024-02-21 22:49 UTC, InvincibleRMC commented on src/surface/gui/gui/widgets/thruster_tester.py
> +        for i in range(MOTOR_COUNT):
but it just feels dirty

2024-02-21 22:51 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +        for i in range(MOTOR_COUNT):
```python
for i, thruster_box in enumerate(self.thruster_boxes):
    thruster_box.pin_input.setText(
        str(params[i].integer_value - SERVO_FUNCTION_OFFSET)
```

But I'm not super opinionated on this

2024-03-08 00:08 UTC, benjaminwp18 requested changes

2024-03-08 00:08 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
Split this out into multiple files

2024-03-08 00:08 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +                self.get_logger().info("pog")
pog

a better debug message could be had here?

2024-03-08 00:08 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +        self.test_cmd_client.get_logger().info(f"Test response: {res.success}, {res.result}")
Is there a way we could reduce the log spam this creates? If I've tested all 8 motors, any other info log gets yeeted off the screen in milliseconds

2024-03-08 00:22 UTC, benjaminwp18 requested changes

2024-03-08 00:22 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/thruster_tester.py
> +            )
tabbing

2024-03-30 17:21 UTC, Tazmania40 commented on src/pi/pi_main/README.md
> +You might need to install geographiclib, as described in pixhawk_communication/README.md.
Are we requiring GeographicLib as a dependency? If so, this language should be more forceful.

2024-06-18 22:54 UTC, closed without merging