ament_pep257
cwruRobotics/rov-24 pull request #130
Opened 2024-02-22 19:39 UTC by InvincibleRMC

# Pull Request

## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adds config file support for ament_pep257. Can remove the submodule when ament_pep257 is updated.

## Related Tickets & Documents

- Related Issue #
#116

2024-02-22 23:35 UTC, benjaminwp18 requested changes
From the diff of your branch's unit test task and main (the green is what this branch added):
![image](https://github.com/cwruRobotics/rov-24/assets/90342856/28031fa7-b9c9-4bdb-a4d7-e24161eb6705)

Is this expected for running these locally? There are lots of other changes, but I don't wanna find all of em, so I'm attaching files. I used `git diff main.txt ament.txt`.

[main.txt](https://github.com/cwruRobotics/rov-24/files/14380376/main.txt)
[ament.txt](https://github.com/cwruRobotics/rov-24/files/14380377/ament.txt)

2024-02-22 23:35 UTC, benjaminwp18 commented on src/surface/rov_flir/test/test_pep257.py
> +"""Test pep257 on this module."""
Should all of the pep257 files have the same comments?

2024-02-22 23:35 UTC, benjaminwp18 commented on .github/workflows/industrial_ci_action.yml
> +          UPSTREAM_WORKSPACE: 'github:clearpathrobotics/robot_upstart#foxy-devel github:InvincibleRMC/ament_pep257#main'
Is it ok to have #*foxy*-devel here?

2024-02-22 23:35 UTC, benjaminwp18 commented on pyproject.toml
> +    ]
one tab less, por favor

2024-02-23 00:10 UTC, InvincibleRMC commented on src/surface/rov_flir/test/test_pep257.py
> +"""Test pep257 on this module."""
Its fine

2024-02-24 19:35 UTC, benjaminwp18 approved these changes

2024-02-24 19:35 UTC, merged