Flood Detection on Pi
cwruRobotics/rov-24 pull request #134
Opened 2024-03-02 21:24 UTC by Tazmania40

# Pull Request

## What type of PR is this? (check all applicable)

- [X] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adding the Pi-based support for the flood detector modules.

## Related Tickets & Documents

- Closes #6

2024-04-19 22:26 UTC, InvincibleRMC commented
TODO make new issue for copying service files / refeactor install file

2024-04-19 22:32 UTC, InvincibleRMC commented
@NoahMollerstuen mentioned that valve manip also using gpio might cause a race condition.

2024-04-19 22:33 UTC, InvincibleRMC commented
Will refactor that on in the future if that is the case

2024-04-20 14:36 UTC, InvincibleRMC commented
Someone should add python3-lgpio to rosdep then add that as a dep.

2024-04-20 17:47 UTC, benjaminwp18 requested changes

2024-04-20 17:47 UTC, benjaminwp18 commented on src/pi/flood_detection/flood_detection/flood_detector.py
> +            msg.flooding = False
```
        flood_reading = lgpio.gpio_read(self.gpio_chip, DETECT_PIN)

        # If any of the sensors detect water, send true to /tether/flooding
        msg = Flooding()
        msg.flooding = (flood_reading == lgpio.HIGH)
        if msg.flooding:
            self.get_logger().error("The ebay is flooding")
```

2024-04-20 17:47 UTC, benjaminwp18 commented on src/pi/flood_detection/flood_detection/gpio_reader_no_ros.py
> +    h = lgpio.gpiochip_open(0)
```suggestion
    gpio_chip = lgpio.gpiochip_open(0)
```

2024-04-20 17:47 UTC, benjaminwp18 commented on src/pi/flood_detection/flood_detection/gpio_reader_no_ros.py
> +    lgpio.gpio_claim_input(h, DETECT_PIN)
```suggestion
    lgpio.gpio_claim_input(gpio_chip, DETECT_PIN)
```

2024-04-20 17:47 UTC, benjaminwp18 commented on src/pi/flood_detection/flood_detection/gpio_reader_no_ros.py
> +    data: int = lgpio.gpio_read(h, DETECT_PIN)
```suggestion
    data: int = lgpio.gpio_read(gpio_chip, DETECT_PIN)
```

2024-04-20 17:47 UTC, benjaminwp18 commented on src/pi/flood_detection/flood_detection/gpio_reader_no_ros.py
> +        data = lgpio.gpio_read(h, DETECT_PIN)
```suggestion
        data = lgpio.gpio_read(gpio_chip, DETECT_PIN)
```

2024-04-20 17:47 UTC, benjaminwp18 commented on src/pi/flood_detection/package.xml
> +  <maintainer email="hwo2@case.edu">Henry Odza</maintainer>
```suggestion
  <maintainer email="rmc170@case.edu">Michael Carlstrom</maintainer>
```

2024-04-20 17:47 UTC, benjaminwp18 commented on src/pi/flood_detection/flood_detection/gpio_reader_no_ros.py
Rename to `gpio_test`

2024-04-20 17:47 UTC, benjaminwp18 commented on src/pi/flood_detection/setup.py
> +            'test = flood_detection.gpio_reader_no_ros:main'
```suggestion
            'test = flood_detection.gpio_test:main'
```

2024-04-20 17:47 UTC, benjaminwp18 commented on src/pi/pi_main/README.md
````suggestion

To kill the `pi_main` background task (**do this before starting the foreground task**):
```bash
sudo systemctl stop pi_main.service
```
````

2024-04-20 18:20 UTC, benjaminwp18 approved these changes

2024-04-20 18:20 UTC, merged