Update transceiver
cwruRobotics/rov-24 pull request #148
Opened 2024-04-25 22:55 UTC by benjaminwp18

# Pull Request

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #133

2024-04-25 23:32 UTC, InvincibleRMC requested changes

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +  uint8_t byteArray[4];
```suggestion
  byte byteArray[4];
```

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
>  #if defined (__AVR_ATmega32U4__)  // Feather 32u4 w/Radio
Extract to header file.

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
Enum?

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
>  unsigned long SCHEDULE[][2] = {
Make #define

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +} bytesUnion;
Maybe floatsToLongs?

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +    ((1 <= stage && stage <= 4) || (6 <= stage && stage <= 9)) &&
Enum stage numbers. and maybe extract to function

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +    Serial.print(pressurePacket[packetIndex]);
toString method of packet

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
>      Serial.print(stage);
abstract toString funtion

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
>    {WAIT, ONE_HOUR    },
Get rid of second profile and use modulo for looping

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +    uint8_t len = sizeof(uintBuf);
Use CONSTANT LEN

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +      char response[32];
String

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +  Serial.print(" >> ");
abstract fo Function

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +  delay(1000);
delete

2024-04-25 23:32 UTC, InvincibleRMC commented on src/float/surface_transceiver/surface_transceiver.ino
> +void sendCommand(char *message) {
string

2024-05-09 21:36 UTC, InvincibleRMC requested changes

2024-05-09 21:36 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +int packetIndex = PKT_PREAMBLE_LEN;
uint8_t

2024-05-09 21:48 UTC, InvincibleRMC requested changes

2024-05-09 21:48 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +    memcpy(pressurePacket + packetIndex, bytesUnion.byteArray, sizeof(float));
See if the union is not neccesary

2024-05-11 01:43 UTC, benjaminwp18 commented on src/float/float_transceiver/float_transceiver.ino
>      Serial.print(stage);
This debug print now uses the printf function:

```cpp
serprintf(
  "Stage #%d, type: %d, start time: %l, max wait time: %l, current time: %l\n",
  currentStage,
  SCHEDULE[currentStage][0],
  stageStartTime,
  SCHEDULE[currentStage][1],
  millis()
);
```

2024-05-11 01:44 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
>      Serial.print(stage);
@benjaminwp18 go home

2024-05-11 01:45 UTC, benjaminwp18 commented on src/float/float_transceiver/float_transceiver.ino
> +    uint8_t len = sizeof(uintBuf);
This actually just sets a default value to `len`, which is then supposed to be overwritten by `rf95.recv(byteBuffer, &len)`
So not constant

2024-05-11 01:46 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +    uint8_t len = sizeof(uintBuf);
Thats fine but rather than calculating it with `sizeof` surely it should be the length of uintBuf?

2024-05-11 01:49 UTC, benjaminwp18 commented on src/float/float_transceiver/float_transceiver.ino
> +int packetIndex = PKT_PREAMBLE_LEN;
Hmmmm https://stackoverflow.com/questions/34891181/for-array-loop-use-int-or-uint8-t

2024-05-11 01:51 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +int packetIndex = PKT_PREAMBLE_LEN;
They are talking about in a for loop. Also it would be one thing if you used int everywhere but having just one is janky.

2024-05-11 15:19 UTC, InvincibleRMC commented on src/float/src/rov_common.cpp
> +void serprintf(const char *input...) {
Should there be some Serial.begin or check that Serial has started here?

2024-05-11 17:41 UTC, InvincibleRMC requested changes

2024-05-11 17:41 UTC, InvincibleRMC commented on src/float/surface_transceiver/surface_transceiver.ino
> +    int numDatapoints = (int) ((len - PKT_PREAMBLE_LEN) / 4);
Bitshifts

2024-05-11 17:41 UTC, InvincibleRMC commented on src/float/surface_transceiver/surface_transceiver.ino
> +  if (len < RH_RF95_MAX_MESSAGE_LEN / 2) {
Bitshift

2024-05-11 17:41 UTC, InvincibleRMC commented on src/float/surface_transceiver/surface_transceiver.ino
> +    int i = PKT_PREAMBLE_LEN;
int i should live in line 140

2024-05-11 17:41 UTC, InvincibleRMC commented on src/float/include/rov_common.hpp
> +#if defined (__AVR_ATmega32U4__)  // Feather 32u4 w/Radio
Move import here for RH_RF95_MAX_MESSAGE_LEN

2024-05-11 18:00 UTC, InvincibleRMC requested changes

2024-05-11 18:00 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +#define PUMP 3
Enums please

2024-05-12 19:49 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
>  /******* Setup Methods (down here cause they're lorge) *******/
lorge -> large

2024-05-12 19:51 UTC, InvincibleRMC commented
I would also recommend started to look into what changes the linter wants.

2024-05-20 21:57 UTC, InvincibleRMC commented on src/float/surface_transceiver/surface_transceiver.ino
> +    int numDatapoints = (int) ((len - (PKT_HEADER_LEN) >> 2));
uint8_t?

2024-05-25 17:38 UTC, benjaminwp18 commented
Remove trailing semicolon from data list

2024-05-25 21:16 UTC, InvincibleRMC requested changes

2024-05-25 21:16 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +byte currentStage = 0;
```suggestion
uint8_t currentStage = 0;
```

2024-05-25 21:16 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +byte profileNum = 0;
```suggestion
uint8_t profileNum = 0;
```

2024-05-25 21:16 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +byte profileHalf = 0;
```suggestion
uint8_t profileHalf = 0;
```

2024-05-25 21:16 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +/******* Setup Methods (down here cause they're lorge) *******/
```suggestion
/******* Setup Methods (down here cause they're large) *******/
```

2024-05-25 21:32 UTC, InvincibleRMC approved these changes
lgtm

2024-05-25 21:32 UTC, merged