Mavros
cwruRobotics/rov-24 pull request #15
Opened 2023-07-18 23:11 UTC by InvincibleRMC

# Pull Request

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [ ] Bug Fix
- [x] Optimization
- [ ] Documentation Update

## Description

Have rewritten our ardusub stack to use mavros. (It is sick!!!)

## Related Tickets & Documents

- Related Issue #
- Closes #

2023-08-17 14:07 UTC, benjaminwp18 requested changes
a review I definitely did yesterday and not today

2023-08-17 14:07 UTC, benjaminwp18 commented on src/pi/pixhawk_communication/launch/mavros_launch.py
> +            # plugin_allowlist allows which mavros nodes get launched default is all of them.
I had two seizures trying to read these comments; could you translate them into english?

2023-08-17 15:30 UTC, InvincibleRMC commented on src/surface/gui/gui/event_nodes/client.py
>          self.connected: bool = False
it does

2023-08-17 15:50 UTC, benjaminwp18 requested changes

2023-09-02 21:08 UTC, benjaminwp18 approved these changes

2023-09-03 00:16 UTC, merged