Humble / Python 3.10
cwruRobotics/rov-24 pull request #16
Opened 2023-07-28 21:30 UTC by InvincibleRMC

# Pull Request

## What type of PR is this? (check all applicable)

- [x] Refactor
- [x] Feature
- [x] Bug Fix
- [x] Optimization
- [x] Documentation Update

## Description

Dear Benjamin,

I hope this markdown finds in you good health. Moving to Humble and Python 3.10 has brought several nice new features especially in the typing department. And has only broken one thing. The submodule we use for i2c communication has an import which no longer exists. However, we were planning on deprecating it anyway as of #5 so as of now it remains unfixed for rookies to work on. This branch is also the foundation of the mavros switch but, figured it would be better left in it's own pr #15. Things that have not worked great in the past have not been super thoroughly tested ej. cameras. I have gone through and used isort so our imports are more professional. I have added a building hotkey for our easy build. Also fixed a janky bug with /task_request service.

TLDR:
FIxed stuff I'm sure we will have a long discussion about all 50 changed files

Best,
Michael Carlstrom

## Related Tickets & Documents

- Related Issue #
#5, #15 
- Closes #
#1

2023-07-29 21:13 UTC, benjaminwp18 requested changes

2023-07-29 21:13 UTC, benjaminwp18 commented on .vscode/easy_all.sh
> +# Done to suppress setup.py warnings
Mention the fact that ROS hasn't updated their packages to use the new build system yet

2023-07-29 21:13 UTC, benjaminwp18 commented on .vscode/easy_build.sh
> +# Done to suppress setup.py warnings
Mention the fact that ROS hasn't updated their packages to use the new build system yet

2023-07-29 21:13 UTC, benjaminwp18 commented on src/surface/surface_main/scripts/ROS2-Install-Humble.sh
> +# Seems to work fine however
Mention the fact that ROS hasn't updated their packages to use the new build system yet
Also fix "depracted" typo

2023-08-16 00:22 UTC, benjaminwp18 requested changes

2023-08-16 00:22 UTC, benjaminwp18 commented on src/surface/keyboard_driver/keyboard_driver/keyboard_driver_node.py
> +                    return
If we're already refactoring the keys, this conversion should probably happen in Keys. Either a method that accepts a key and spits out a status, or a dictionary that does the same thing.

2023-08-16 00:22 UTC, benjaminwp18 commented on src/pi/pixhawk_communication/pixhawk_communication/pixhawk_communication.py
> +            qos_profile_system_default
Is it fine for these to be the same? I can't test this bit

2023-08-16 00:25 UTC, InvincibleRMC commented on src/pi/pixhawk_communication/pixhawk_communication/pixhawk_communication.py
> +            qos_profile_system_default
huh?

2023-08-16 01:40 UTC, benjaminwp18 approved these changes

2023-08-16 01:41 UTC, merged