Add livestream gui
cwruRobotics/rov-24 pull request #181
Opened 2024-05-26 19:59 UTC by NoahMollerstuen

# Pull Request

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Adds a gui to be displayed on the MATE livestream. Use the new `competition_launch.py` launch file in `surface_main`.

## Related Tickets & Documents

- Related Issue #
- Closes #118

2024-05-26 20:23 UTC, InvincibleRMC requested changes
Add back switching depth camera.

2024-05-26 20:23 UTC, InvincibleRMC commented on src/surface/surface_main/launch/competition_launch.py
> +    gui_path: str = get_package_share_directory('gui')
```suggestion
    gui_path = get_package_share_directory('gui')
```

2024-05-26 20:23 UTC, InvincibleRMC commented on src/surface/surface_main/launch/competition_launch.py
> +    surface_path: str = get_package_share_directory('surface_main')
```suggestion
    surface_path = get_package_share_directory('surface_main')
```

2024-05-26 20:27 UTC, NoahMollerstuen commented
> Add back switching depth camera.

I took it out intentionally, I don't think we're planning to have a depth cam anymore. Unless we want it for something other than modelling.

2024-05-26 20:42 UTC, InvincibleRMC commented
> > Add back switching depth camera.
> 
> I took it out intentionally, I don't think we're planning to have a depth cam anymore. Unless we want it for something other than modelling.

We are trying to add it back so we can have a back camera just in case.

2024-05-27 00:55 UTC, NoahMollerstuen commented
> > > Add back switching depth camera.
> > 
> > 
> > I took it out intentionally, I don't think we're planning to have a depth cam anymore. Unless we want it for something other than modelling.
> 
> We are trying to add it back so we can have a back camera just in case.

Aight I added it back

2024-05-27 17:14 UTC, InvincibleRMC approved these changes
lgtm.

2024-05-27 18:41 UTC, merged