Remove switchable video
cwruRobotics/rov-24 pull request #182
Opened 2024-05-28 21:26 UTC by benjaminwp18

# Pull Request

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Removes video switching from the GUI and adds arm/disarm buttons to the controllers

2024-05-28 21:37 UTC, InvincibleRMC requested changes
Use declare_paremeter. remove threading nonsense

2024-05-30 20:15 UTC, InvincibleRMC requested changes

2024-05-30 20:15 UTC, InvincibleRMC commented on src/surface/flight_control/flight_control/manual_control_node.py
> +from rclpy.parameter import Parameter
```suggestion
```

2024-05-30 20:15 UTC, InvincibleRMC commented on src/surface/flight_control/flight_control/manual_control_node.py
> +        mode_param = self.declare_parameter(CONTROLLER_MODE_PARAM, Parameter.Type.INTEGER)
```suggestion
        mode_param = self.declare_parameter(CONTROLLER_MODE_PARAM)
```

2024-05-30 20:15 UTC, InvincibleRMC commented on src/surface/flight_control/flight_control/manual_control_node.py
> +        controller_mode = ControllerMode(mode_param.get_parameter_value().integer_value)
```suggestion
        controller_mode = ControllerMode(mode_param.value)
```

2024-05-30 20:15 UTC, InvincibleRMC commented on src/surface/flight_control/flight_control/manual_control_node.py
> +    def toggle_cameras(self, msg: Joy) -> None:
```suggestion
    def camera_toggle(self, msg: Joy) -> None:
```

2024-05-31 13:32 UTC, benjaminwp18 commented on src/surface/flight_control/flight_control/manual_control_node.py
> +    def toggle_cameras(self, msg: Joy) -> None:
Functions should start with verbs
I call "eat_walrus()" on my Walrus-eating robot, not "walrus_eat()"

2024-06-01 17:06 UTC, InvincibleRMC requested changes

2024-06-01 17:06 UTC, InvincibleRMC commented on src/surface/flight_control/flight_control/manual_control_node.py
> +        if controller_mode == ControllerMode.TOGGLE_CAMERAS:
```suggestion
        if controller_mode is ControllerMode.TOGGLE_CAMERAS:
```

2024-06-01 17:14 UTC, InvincibleRMC approved these changes

2024-06-01 17:14 UTC, merged