Add ambient pressure
cwruRobotics/rov-24 pull request #184
Opened 2024-06-01 19:16 UTC by InvincibleRMC

# Pull Request

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

## Related Tickets & Documents

- Related Issue #
- Closes #

2024-06-01 19:17 UTC, InvincibleRMC commented on src/float/float_transceiver/float_transceiver.ino
> +    char judgePacketBuffer[30];
@benjaminwp18 extract 30 to some constant?

2024-06-03 13:01 UTC, benjaminwp18 commented on src/float/float_transceiver/float_transceiver.ino
> +    char judgePacketBuffer[30];
added

2024-06-15 20:51 UTC, benjaminwp18 requested changes

2024-06-15 20:51 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/float_comm.py
> +        FloatComm.counter += 1
Make instance variable

2024-06-15 20:51 UTC, benjaminwp18 commented on src/surface/transceiver/transceiver/serial_reader.py
> +    def __init__(self, queue_size: int = 5) -> None:
```suggestion
    def __init__(self, queue_size: int = AVERAGE_QUEUE_LEN) -> None:
```

2024-06-15 20:51 UTC, benjaminwp18 commented on src/surface/transceiver/transceiver/serial_reader.py
```suggestion

AVERAGE_QUEUE_LEN = 5
```

2024-06-15 20:51 UTC, benjaminwp18 commented on src/surface/transceiver/transceiver/serial_reader.py
> +        ros_single = ROS_PACKET + "SINGLE"
Make this a constant

2024-06-15 21:17 UTC, benjaminwp18 approved these changes

2024-06-15 21:17 UTC, merged