Use livesteam gui as pilot gui
cwruRobotics/rov-24 pull request #188
Opened 2024-06-08 23:25 UTC by InvincibleRMC

Use livestream gui for pilot gui and move flood warning to operator gui. Add fun surprise to flood warning :)

2024-06-08 23:25 UTC, InvincibleRMC commented
Oops I'm logged in as Michael

2024-06-09 15:45 UTC, benjaminwp18 requested changes

2024-06-09 15:45 UTC, benjaminwp18 commented on src/surface/gui/gui/sounds/alarm.wav
oh lordy

I see these possible downsides:
- This file is lorge
- It might get screwy and loop forever
- Loading a WAV into memory might steal our precious gigabytes

Whadya think?

2024-06-09 15:45 UTC, benjaminwp18 commented on src/surface/gui/gui/operator_app.py
I added the IP & Heartbeat widgets to the main tab as well as the temp sensor in main
It'd be cool if they were still there

2024-06-09 15:45 UTC, benjaminwp18 commented on src/surface/gui/gui/pilot_app.py
> +    def apply_monitor_config(self, gui_id: str) -> None:
Make `gui_id` an enum

2024-06-09 15:45 UTC, benjaminwp18 commented on src/surface/gui/gui/pilot_app.py
> +                920, 690
Does this make the cams smaller on the GUI?
Small == bad?

2024-06-09 16:28 UTC, NoahMollerstuen commented on src/surface/gui/gui/sounds/alarm.wav
> This file is lorge

It's 1% the size of than one of the simulation meshes

> Loading a WAV into memory might steal our precious gigabytes

I think we can afford the 1MB of RAM

> It might get screwy and loop forever

It seems to end properly after one loop. And if ever goes off, procedure is to E-stop, in which case it doesn't really matter if we have to mute or close the gui

2024-06-09 16:29 UTC, NoahMollerstuen commented on src/surface/gui/gui/pilot_app.py
> +                920, 690
It makes them fit on the gui. This is as large as I could get them. There's still some spacing between them horizontally that we would ideally figure out how to get rid of.

2024-06-09 16:29 UTC, NoahMollerstuen commented on src/surface/gui/gui/operator_app.py
Oop

2024-06-09 16:49 UTC, NoahMollerstuen commented on src/surface/gui/gui/pilot_app.py
> +            return
Yes, if you launch the pilot gui with only two monitors

2024-06-09 18:44 UTC, benjaminwp18 requested changes

2024-06-09 18:44 UTC, benjaminwp18 commented on src/surface/gui/gui/pilot_app.py
>  def make_bottom_bar() -> QHBoxLayout:
Add docstring and move into PilotApp

2024-06-09 18:44 UTC, benjaminwp18 commented on src/surface/gui/gui/pilot_app.py
> +THREE_MONITOR_CONFIG = {GuiType.PILOT: 2, GuiType.LIVESTREAM: 1}
```suggestion
TWO_MONITOR_CONFIG: dict[GuiType, int | None] = {GuiType.PILOT: None, GuiType.LIVESTREAM: 1}
THREE_MONITOR_CONFIG: dict[GuiType, int | None] = {GuiType.PILOT: 2, GuiType.LIVESTREAM: 1}
```

2024-06-09 18:44 UTC, benjaminwp18 commented on src/surface/gui/gui/pilot_app.py
> +    def apply_monitor_config(self, gui_type: GuiType) -> None:
Add docstring

2024-06-09 19:02 UTC, benjaminwp18 approved these changes
lgtm

2024-06-09 19:18 UTC, merged