Murder task selector
cwruRobotics/rov-24 pull request #74
Opened 2023-12-02 19:40 UTC by benjaminwp18

# Pull Request

## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
- Remove task selector
- Add converter to handle pixhawk channels & converting from [-1,1] to [1100,1900]
- Replace task selector with manual control node & stub autodocker that can run simultaneously with manual control

## Related Tickets & Documents

- Related Issue #37
- Closes #37

2023-12-02 20:01 UTC, InvincibleRMC commented on src/surface/teleop/teleop/auto_docking_node.py
> +        # Add cam frame subscriber here to act as control loop for auto docking
or camera subscriber

2023-12-02 20:02 UTC, InvincibleRMC commented on src/surface/surface_main/launch/surface_operator_launch.py
>      # Launches Task Selector
launches task selector 🤨

2023-12-02 21:54 UTC, InvincibleRMC requested changes

2023-12-02 21:54 UTC, InvincibleRMC commented on src/surface/flight_control/flight_control/auto_docking_node.py
> +            AutonomousFlight, '/auto_docker_control', self.task_control_callback)
remove leading forward /

2023-12-02 21:54 UTC, InvincibleRMC commented on src/surface/flight_control/flight_control/auto_docking_node.py
> +            AutonomousFlight, '/auto_docker_control', self.task_control_callback)
use better name scrub

2023-12-02 21:54 UTC, InvincibleRMC commented on src/surface/flight_control/flight_control/auto_docking_node.py
> +        self.running = request.start
TODO maybe test threading?

2023-12-02 21:54 UTC, InvincibleRMC commented on src/surface/flight_control/test/test_manual_control.py
> +from flight_control.pixhawk_instruction import PixhawkInstruction, FORWARD_CHANNEL, \
paren import pls

2023-12-04 21:00 UTC, benjaminwp18 commented on src/surface/flight_control/flight_control/auto_docking_node.py
> +        self.running = request.start
Use something thread safe instead of a bool flag

2023-12-04 22:38 UTC, benjaminwp18 commented on src/surface/flight_control/flight_control/auto_docking_node.py
> +        self.running = request.start
knope
https://stackoverflow.com/questions/69617271/python-boolean-thread-safe

2023-12-04 23:02 UTC, InvincibleRMC approved these changes
lgtm!

2023-12-04 23:09 UTC, merged