Flood Visualization
cwruRobotics/rov-24 pull request #83
Opened 2023-12-16 19:42 UTC by Tazmania40

# Pull Request

## What type of PR is this? (check all applicable)

- [X] Refactor
- [X] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Adds functionality that detects flooding on a ROS2 topic /flooding and displays that information on the pilot display as a red dot rather than the default green state. The functionality is latching until the GUI is reset, as afaik, there isn't really a reason where a flood would not cause a system reset of some kind... 

## Related Tickets & Documents

- Closes #7

2023-12-18 18:48 UTC, InvincibleRMC requested changes
Add remapping for flooding topic and update README.md for gui package.

2023-12-18 18:48 UTC, InvincibleRMC commented on src/surface/gui/gui/widgets/flood_visual.py
> +        self.subscription: GUIEventSubscriber = GUIEventSubscriber(Flooding,
No forward /

2023-12-18 18:55 UTC, InvincibleRMC commented
On linux the Qlabel of emojis does not seem to work. Surely there is some QShape thing that can be used as circles or something.

2023-12-18 20:53 UTC, Tazmania40 commented
Appears emoji support is more spotty than I thought... There unfortunately isn't a good way to do a QShape as described, but I'll look into it further.

2023-12-18 22:43 UTC, InvincibleRMC commented
> Appears emoji support is more spotty than I thought... There unfortunately isn't a good way to do a QShape as described, but I'll look into it further.

I think something from here might work.

https://likegeeks.com/pyqt5-drawing-tutorial/#Draw_a_circle

2024-01-27 20:00 UTC, Tazmania40 commented on src/surface/gui/gui/widgets/flood_visual.py
> +        self.subscription: GUIEventSubscriber = GUIEventSubscriber(Flooding,
Fixed

2024-01-27 20:52 UTC, benjaminwp18 requested changes

2024-01-27 20:52 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/flood_visual.py
> +            self.subscription.get_logger().error("Robot is actively flooding, do something!")
Add an `else` clause that removes the flooding warning if there's no flooding
Remove the font changing code here; it's now unused

2024-01-27 20:52 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/flood_visual.py
> +        self.mylayout.addWidget(self.label)
Remove redundant comments
Rename `self.mylayout` to something else. `self.flood_layout`?

2024-01-27 20:52 UTC, benjaminwp18 commented on src/surface/gui/gui/widgets/flood_visual.py
> +class FloodVisual(QWidget):
`FloodVisual` sounds awkward to me. `FloodWarning`? `FloodAlertWidget`?

2024-01-27 20:58 UTC, Tazmania40 commented on src/surface/gui/gui/widgets/flood_visual.py
> +        self.mylayout.addWidget(self.label)
renamed, "redundant comments removed"

2024-01-27 20:59 UTC, Tazmania40 commented on src/surface/gui/gui/widgets/flood_visual.py
> +            self.subscription.get_logger().error("Robot is actively flooding, do something!")
Added an `else` clause with a warning that it reset itself.

2024-01-27 21:13 UTC, benjaminwp18 requested changes
Rename `flood_visual.py` to `flood_warning.py` to match new class name

2024-01-27 21:37 UTC, benjaminwp18 approved these changes

2024-01-27 21:40 UTC, InvincibleRMC approved these changes

2024-01-27 21:41 UTC, merged